### PR TITLE
Italian localization

### PR DESCRIPTION
**Pull request by THEBOSSMAGNUS**

### CODE REVIEW

**Comment by farag2** [comment]
Wow, thanks! but you forget about the JSON file). To let you translate it easier, we will spit it into files. Wait for a few days please.

**Comment by farag2** [comment]
You accidentally edited CHANGELOG.md. :)

**Comment by THEBOSSMAGNUS** [comment]
> You accidentally edited CHANGELOG.md. :)

Yes, little issues with github desktop

**Comment by farag2** [comment]
We've spitted the main JSON into files to let users translate into their native language easier. So if you're ready. :)

https://github.com/Sophia-Community/SophiApp/tree/master/SophiApp/SophiApp/Resources

**Comment by THEBOSSMAGNUS** [comment]
There is some program for translate this, something like: https://docs.microsoft.com/it-it/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads ?

**Comment by THEBOSSMAGNUS** [comment]
I started, it's a loooong process. Wish me good luck!

**Comment by farag2** [comment]
⭐

**Comment by THEBOSSMAGNUS** [comment]
I'm doing it correctly?

**Comment by farag2** [comment]
You need to create a new file UIData_IT.json and not translate already existed EN. :)

**Comment by THEBOSSMAGNUS** [comment]
Now it's ok?

**Comment by farag2** [comment]
Yes. But remove `#(?)` in your new JSON

**Comment by THEBOSSMAGNUS** [comment]
image
\u0027s ?

**Comment by farag2** [comment]
The very first string.

**Comment by THEBOSSMAGNUS** [comment]
> The very first string.



> image \u0027s ?

What I should do?

**Comment by THEBOSSMAGNUS** [comment]
I also want to report that line 327 is in German

**Comment by farag2** [comment]
The very first string in your file. It's marked red.

**Comment by farag2** [comment]
[Yes. But remove `#(?)` in your new JSON ](https://github.com/Sophia-Community/SophiApp/pull/55/files#diff-03197c153c12fa7804a78014af535eee1f3ea38868747227a1137406e4de3f8bR1)

**Comment by farag2** [comment]
https://github.com/Sophia-Community/SophiApp/blob/0cc52c427ed447dd5ce36cf3bad0db5d69446913/SophiApp/SophiApp/Resources/UIData_IT.json#L1

**Comment by THEBOSSMAGNUS** [comment]
removed

**Comment by farag2** [comment]
> I also want to report that line 327 is in German

Fixed.

**Comment by THEBOSSMAGNUS** [comment]
image
This function doesn't exist in the app

**Comment by farag2** [comment]
> image This function doesn't exist in the app

It does exist. Just open Settings and enable advanced functions. The appropriate ID will be visible.

**Review by farag2 — COMMENTED** [review]
Great work!

**Comment by THEBOSSMAGNUS** [comment]
Someway to compile the app and test of stringe are ok?

**Comment by farag2** [comment]
If you wish, you may compile it by yourself: just create a new release with 1.0.0.54 tag. The actions will be triggered automatically!
If you want, I may do it. :)

**Comment by THEBOSSMAGNUS** [comment]
> If you wish, you may compile it by yourself: just create a new release with 1.0.0.54 tag. The actions will be triggered automatically! If you want, I may do it. :)

?

**Comment by farag2** [comment]
> > If you wish, you may compile it by yourself: just create a new release with 1.0.0.54 tag. The actions will be triggered automatically! If you want, I may do it. :)
> 
> ?

You may trigger the compiler in cloud. There is no need to have a local VS installed.

**Comment by THEBOSSMAGNUS** [comment]
image
Like that?

**Comment by farag2** [comment]
> image Like that?

Like but not what we need. We already have one: https://github.com/Sophia-Community/SophiApp/blob/master/.github/workflows/SophiApp.yml

We do not use .NET Core. Dunno why create it. Look: I will create a new tag in this repo

**Comment by farag2** [comment]
Compiling: https://github.com/Sophia-Community/SophiApp/runs/6083244518?check_suite_focus=true

**Comment by farag2** [comment]
I forgot that IT support wasn't added. We cannot enable it in the UI. I will ask my pal to implement it tomorrow. :)

**Comment by THEBOSSMAGNUS** [comment]
> I forgot that IT support wasn't added. We cannot enable it in the UI. I will ask my pal to implement it tomorrow. :)

oh, thank you!

**Comment by THEBOSSMAGNUS** [comment]
- [ ] Early translation
- [ ] Implement in gui and dev things
- [ ] Test (i probably commit some error/skip some strings)
- [ ] Release

**Comment by THEBOSSMAGNUS** [comment]
done!

**Pull request merged**
