### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by farag2** [comment]
I updated this string: https://github.com/Sophia-Community/SophiApp/blob/33fa061d80b4f83101a8312a3941372dc0b0f2d9/SophiApp/SophiApp/Resources/UIData.json#L2561

**Comment by Henry2o1o** [comment]
SophiApp 1.0.0.52 does not start
I have already checked translations

**Comment by farag2** [comment]
Fixed all lines 1 minutes ago. In process of compiling
https://github.com/Sophia-Community/SophiApp/runs/5963589994?check_suite_focus=true

**Comment by farag2** [comment]
https://github.com/Sophia-Community/SophiApp/commit/e798905c6f04a58af57512e259ef54a08d08c197

What caused the exception.

**Comment by farag2** [comment]
You place a mirror quotation. But you need to use \" only, from the beginning and in the end of expression

**Pull request merged**
