### PR TITLE
Add winget as an install method in readme

### PR DESCRIPTION
**Pull request by TheBossMagnus**

### CODE REVIEW

**Comment by farag2** [comment]
Blocking issue #2931

https://github.com/microsoft/winget-cli/issues/2931#issuecomment-1426050742

**Comment by farag2** [comment]
The issue was added to the [v1.5-Client](https://github.com/microsoft/winget-cli/milestone/39) milestone

**Comment by TheBossMagnus** [comment]
my bad, i was doing some cleanup...

**Comment by farag2** [comment]
It works in https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview
Waiting for 1.5 release :cat:

**Comment by TheBossMagnus** [comment]
redone in #189

**Pull request closed without merging**
