### PR TITLE
add scoop installation method to README.md

### PR DESCRIPTION
**Pull request by KrisSchneider**
I added SophiApp to scoop.sh

### CODE REVIEW

**Comment by farag2** [comment]
Thank you! I'll need to edit every readme,md. :)

**Comment by KrisSchneider** [comment]
> Thank you! I'll need to edit every readme,md. :)

You're welcome 😊

**Comment by KrisSchneider** [comment]
Silly me I forgot to add Scoop to this. Thanks
### How to download SophiApp via PowerShell/Chocolatey/Scoop

**Comment by KrisSchneider** [comment]
@farag2 could you please reopen the pull request I made some edits to the **Scoop** section that are very important.

**Comment by farag2** [comment]
It cannot be reopened actually, but reverted. You'll have to open a new one. this is git...

**Comment by farag2** [comment]
and make any new changes to fix what you think should be fixed.

**Comment by KrisSchneider** [comment]
oh ok

**Pull request merged**
