### PR TITLE
Add Simplified Chinese for README.md

### PR DESCRIPTION
**Pull request by Colgrave34**
Hello, 
This pull request mainly adds a Simplified Chinese translate for README.md. Secondly, I have fixed some small format problem with the translated page link.

### CODE REVIEW

**Comment by farag2** [comment]
Awesome! I will check soon. Also, I'm going to add this translation to SophiApp 2.0 too. 2.0 is a deep development stage.

**Comment by Colgrave34** [comment]
Thanks! Are there any big changes for 2.0 for the README files?

**Comment by farag2** [comment]
Not for Readme)

**Comment by farag2** [comment]
I'll ping when I have finished template.

**Pull request merged**
