### PR TITLE
Create DE.xaml

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by farag2** [comment]
Thank you for your work but you forgot a little file: https://github.com/Sophia-Community/SophiApp/blob/master/SophiApp/SophiApp/Resources/UIData.json 😹 
Actually, you're rushing things: the description isn't finished yet and wil be improved. But I won't close the PR until all localization will have the complete form.

**Comment by Henry2o1o** [comment]
> Thank you for your work but you forgot a little file: https://github.com/Sophia-Community/SophiApp/blob/master/SophiApp/SophiApp/Resources/UIData.json 😹 Actually, you're rushing things: the description isn't finished yet and wil be improved. But I won't close the PR until all localization will have the complete form.

I have already seen the file and have not forgotten it, but unfortunately it is not so small 😮

**Comment by farag2** [comment]
Welcome to our world))

**Comment by farag2** [comment]
When you will be able to translate the whole UI? We're very near the stable release, aiming on March.

**Comment by csidirop** [comment]
@Henry2o1o do you need help with this? Are you still working on the translation? 
I could offer some help.

**Comment by farag2** [comment]
@csidirop, <https://github.com/Sophia-Community/SophiApp/discussions/32#discussioncomment-2128926>
You may join him. but only after we will be confident that this is the final translation version. We're testing the first build supported Windows 11. We will inform you all when you may start translating.

**Comment by csidirop** [comment]
> @csidirop, <https://github.com/Sophia-Community/SophiApp/discussions/32#discussioncomment-2128926>
> You may join him. but only after we will be confident that this is the final translation version. We're testing the first build supported Windows 11. We will inform you all when you may start translating.

Okay, just mention me when you've figured it out.

**Comment by farag2** [comment]
Hi, guys. We're pretty close to the first full stable release. As soon as I will be confident that that build will be RTM 🤣 , I will let you know, providing you the configured JSON to add the DE laocalization.

**Comment by farag2** [comment]
@csidirop, @Henry2o1o, are you ready? 😸 
 
<https://github.com/Sophia-Community/SophiApp/tree/master/SophiApp/SophiApp/Localizations>
<https://github.com/Sophia-Community/SophiApp/blob/master/SophiApp/SophiApp/Resources/UIData.json>

You may get in touch me me if you have any questions via Telegram: https://t.me/sanctuary_d

**Comment by farag2** [comment]
@csidirop, hi. We just wonder how much time will take you to finish it?

**Comment by csidirop** [comment]
> @csidirop, hi. We just wonder how much time will take you to finish it? 

Hi, I wasn't at home this weekend but i can start this week. Because i have a fulltime job I can only work afterworks. 

But its not that much to translate, so maybe a few days. Is that okay?

**Comment by farag2** [comment]
@csidirop, if you think, this is not much, OK )). As for me, I do not think so. As you may see, we already prepared the DE.xml file for you. So it's OK for us of course to wait until you finish it up. There are still a few bugs left in 1.0.0.31 build. :)

**Comment by farag2** [comment]
@csidirop, hi! How is your progress? :) Or you haven't got to translating?

**Comment by csidirop** [comment]
Hi @farag2, I already finished [DE.xaml](https://github.com/csidirop/SophiApp/blob/master/SophiApp/SophiApp/Localizations/DE.xaml) but only around one third through UIData.json.

**Comment by farag2** [comment]
@csidirop, great! thanks. As I might see, Ive changed a few strings. FYI.

https://github.com/Sophia-Community/SophiApp/commits/master/SophiApp/SophiApp/Resources/UIData.json

**Comment by farag2** [comment]
@csidirop, is there an end in sight? :)

**Comment by csidirop** [comment]
Actually not. I'm still at about 30% of UIdata. And I wont have more time till mid next week. 
I am really sorry!

**Comment by farag2** [comment]
@csidirop, no problem. Do it at you free time, of course. I'm just controling thr process. :) We still fixing the last 2 bugs.

**Comment by farag2** [comment]
@DAmNRelentless, you may team up with @csidirop. Two heads are better then one. 👍I think, we did our best and finished polishing the release version. Just waiting for the Ukranian translation and German one.

**Comment by farag2** [comment]
@csidirop, hi, any chance to see the result this week? 🌵

**Comment by farag2** [comment]
@csidirop Hi, again. As you may see, we've totally updated the JSON file by adding Ukranian translation and many more fixes. Do not forget to update it before editing!

**Comment by farag2** [comment]
The German translation was ordered and implemented. Closing...

**Pull request closed without merging**
