### PR TITLE
SophiApp.ico

### PR DESCRIPTION
**Pull request by kezcik**
includes 256x256. 64x64, 32x32 and 16x16 ico files

### CODE REVIEW

**Comment by farag2** [comment]
Thanks. Bu the file resolution is still 32x32. I do not understand something?

**Comment by farag2** [comment]
https://github.com/Sophia-Community/SophiApp/releases/tag/1.0.77

Converted by myself. Please rate.

**Comment by farag2** [comment]
Merged in #101

**Comment by kezcik** [comment]
I posted it again however I individually converted the SVG file for each
resolution and provided you with a link to a GPLv3 icon editor for you to
review the change and then requested a new pull request #102

**Pull request closed without merging**
